//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savoia.Desencalha.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Savoia.Desencalha.Domain.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha algum filtro para pesquisa.
        /// </summary>
        public static string COMUM_PESQUISA_PREENCHA_CAMPO {
            get {
                return ResourceManager.GetString("COMUM_PESQUISA_PREENCHA_CAMPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem registros associados. Impossivel exclusão.
        /// </summary>
        public static string COMUM_REGISTRO_ASSOCIADO {
            get {
                return ResourceManager.GetString("COMUM_REGISTRO_ASSOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso.
        /// </summary>
        public static string COMUM_REGISTRO_ATUALIZADO_SUCESSO {
            get {
                return ResourceManager.GetString("COMUM_REGISTRO_ATUALIZADO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluido com sucesso.
        /// </summary>
        public static string COMUM_REGISTRO_EXCLUIDO_SUCESSO {
            get {
                return ResourceManager.GetString("COMUM_REGISTRO_EXCLUIDO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existente.
        /// </summary>
        public static string COMUM_REGISTRO_EXISTENTE {
            get {
                return ResourceManager.GetString("COMUM_REGISTRO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inserido com sucesso.
        /// </summary>
        public static string COMUM_REGISTRO_INSERIDO_SUCESSO {
            get {
                return ResourceManager.GetString("COMUM_REGISTRO_INSERIDO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros atualizados com sucesso.
        /// </summary>
        public static string COMUM_REGISTROS_ATUALIZADOS_SUCESSO {
            get {
                return ResourceManager.GetString("COMUM_REGISTROS_ATUALIZADOS_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request incorreto.
        /// </summary>
        public static string COMUM_REQUEST_INVALIDO {
            get {
                return ResourceManager.GetString("COMUM_REQUEST_INVALIDO", resourceCulture);
            }
        }
    }
}
